stages:
  - test

include:
  # Secret Detection
  - template: Security/Secret-Detection.gitlab-ci.yml

  # Static Application Security Testing (SAST)
  - template: Security/SAST.gitlab-ci.yml

  # Dependency / Dependency Scanning (SCA)
  - template: Security/Dependency-Scanning.gitlab-ci.yml


# Optional: globale Optimierungen
variables:
  # aktiviert tiefere historische Analyse für Secrets
  SECRET_DETECTION_HISTORIC_SCAN: "true"

  # reduziert False Positives in Dependency Scanning etwas
  DS_DEFAULT_ANALYZERS: "all"


