services:
  db:
    image: postgres:16
    container_name: project_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: project_backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/appdb
      - IMAGE_DIR=/app/static/images
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - static_images_volume:/app/static/images

  frontend:
    build: ./frontend
    container_name: project_frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_HOST=localhost

volumes:
  db_data:
  static_images_volume:

networks:
  app-network:
    driver: bridge
