services:
  db:
    image: postgres:16
    container_name: usecase-management_db-dev-${DEV_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"  # NUR localhost!
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: usecase-management_backend-${DEV_USER}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - IMAGE_DIR=${IMAGE_DIR}
      - ENV=${ENV}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DB_READER_USER=${DB_READER_USER}
      - DB_READER_PASS=${DB_READER_PASS}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASS=${DB_ADMIN_PASS}
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8000"  # NUR localhost!
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - static_images_volume_dev:/app/static/images
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: usecase-management_frontend-${DEV_USER}
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:3000" # NUR localhost
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

volumes:
  db_data_dev:
    name: usecase-management_db_data_dev_${DEV_USER}
  static_images_volume_dev:
    name: usecase-management_static_images_dev_${DEV_USER}

networks:
  app-network:
    name: usecase-management_network_${DEV_USER}
    driver: bridge
