apiVersion: v1
kind: Service
metadata:
  name: usecase-management-db
spec:
  selector:
    app: usecase-management-db
  ports:
    - port: 5432
      name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usecase-management-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storage.className }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usecase-management-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usecase-management-db
  template:
    metadata:
      labels:
        app: usecase-management-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.db | quote }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: usecase-management-db-pvc
