apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usecase-management
  annotations:
    cert-manager.io/cluster-issuer:
      {{ .Values.ingress.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: usecase-management-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: usecase-management-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: usecase-management-frontend
                port:
                  number: 80
