"""added more attributes to subusecases

Revision ID: 12445741ab53
Revises: 8b74282f51ca
Create Date: 2026-04-09 10:52:42.172367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12445741ab53'
down_revision: Union[str, Sequence[str], None] = '8b74282f51ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subUseCases', sa.Column('objective', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('inputs', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('outputs', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('potential_risks', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('distinction_from_other_sucs', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('dependency_of_other_sucs', sa.String(), nullable=True))
    op.add_column('subUseCases', sa.Column('assumptions', sa.String(), nullable=True))
    op.drop_column('subUseCases', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subUseCases', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subUseCases', 'assumptions')
    op.drop_column('subUseCases', 'dependency_of_other_sucs')
    op.drop_column('subUseCases', 'distinction_from_other_sucs')
    op.drop_column('subUseCases', 'potential_risks')
    op.drop_column('subUseCases', 'outputs')
    op.drop_column('subUseCases', 'inputs')
    op.drop_column('subUseCases', 'objective')
    # ### end Alembic commands ###
