"""added_version_updated-by_and_updated-at

Revision ID: 173205317f0f
Revises: e715973110a5
Create Date: 2026-06-23 08:48:29.739729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '173205317f0f'
down_revision: Union[str, Sequence[str], None] = 'e715973110a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TYPE category RENAME TO propertygroupcategory'
    )
    op.add_column('roles', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.String(), nullable=False, server_default='system'))
    op.add_column('standards', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('standards', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('standards', sa.Column('updated_by', sa.String(), nullable=False, server_default='system'))
    op.add_column('subUseCases', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subUseCases', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subUseCases', sa.Column('updated_by', sa.String(), nullable=False, server_default='system'))
    op.add_column('transactions', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('transactions', sa.Column('updated_by', sa.String(), nullable=False, server_default='system'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TYPE propertygroupcategory RENAME TO category'
    )
    op.drop_column('transactions', 'updated_by')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'version')
    op.drop_column('subUseCases', 'updated_by')
    op.drop_column('subUseCases', 'updated_at')
    op.drop_column('subUseCases', 'version')
    op.drop_column('standards', 'updated_by')
    op.drop_column('standards', 'updated_at')
    op.drop_column('standards', 'version')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'version')
    # ### end Alembic commands ###
