"""Added fields to Transactions

Revision ID: 1e0637eeb92c
Revises: 12445741ab53
Create Date: 2026-04-14 12:31:16.713226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0637eeb92c'
down_revision: Union[str, Sequence[str], None] = '12445741ab53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('process_number', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('related_class_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('data_carrier', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('dataformat_available', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('dataformat', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('timing', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('policies', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('data_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'data_size')
    op.drop_column('transactions', 'policies')
    op.drop_column('transactions', 'timing')
    op.drop_column('transactions', 'dataformat')
    op.drop_column('transactions', 'dataformat_available')
    op.drop_column('transactions', 'data_carrier')
    op.drop_column('transactions', 'related_class_id')
    op.drop_column('transactions', 'process_number')
    # ### end Alembic commands ###
