"""added conx_id to subusecase

Revision ID: 3e877b8134ba
Revises: ec428c55e044
Create Date: 2026-04-21 10:43:52.670331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e877b8134ba'
down_revision: Union[str, Sequence[str], None] = 'ec428c55e044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subUseCases', sa.Column('conx_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subUseCases', 'conx_id')
    # ### end Alembic commands ###
