"""changed propertygruop name to jsonb

Revision ID: 696a57f987bf
Revises: fa76906a529d
Create Date: 2026-06-11 14:37:02.193992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '696a57f987bf'
down_revision: Union[str, Sequence[str], None] = 'fa76906a529d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propertyGroups', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_propertyGroups_name'), 'propertyGroups', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propertyGroups_name'), table_name='propertyGroups')
    op.alter_column('propertyGroups', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
