"""add subUseCase_roles with motivation and goal

Revision ID: 79d5178f3dd0
Revises: 
Create Date: 2026-04-08 11:25:18.558944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d5178f3dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.add_column('subUseCase_roles', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('subUseCase_roles', sa.Column('motivation', sa.String(), nullable=True))
    op.add_column('subUseCase_roles', sa.Column('goal', sa.String(), nullable=True))
    op.alter_column('subUseCase_roles', 'subUseCase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subUseCase_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_subUseCase_roles_id'), 'subUseCase_roles', ['id'], unique=False)
    op.drop_constraint(op.f('subUseCase_roles_subUseCase_id_fkey'), 'subUseCase_roles', type_='foreignkey')
    op.drop_constraint(op.f('subUseCase_roles_role_id_fkey'), 'subUseCase_roles', type_='foreignkey')
    op.create_foreign_key(None, 'subUseCase_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subUseCase_roles', 'subUseCases', ['subUseCase_id'], ['id'], ondelete='CASCADE')
    op.add_column('subUseCases', sa.Column('short_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_subUseCases_short_name'), 'subUseCases', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subUseCases_short_name'), table_name='subUseCases')
    op.drop_column('subUseCases', 'short_name')
    op.drop_constraint(None, 'subUseCase_roles', type_='foreignkey')
    op.drop_constraint(None, 'subUseCase_roles', type_='foreignkey')
    op.create_foreign_key(op.f('subUseCase_roles_role_id_fkey'), 'subUseCase_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('subUseCase_roles_subUseCase_id_fkey'), 'subUseCase_roles', 'subUseCases', ['subUseCase_id'], ['id'])
    op.drop_index(op.f('ix_subUseCase_roles_id'), table_name='subUseCase_roles')
    op.alter_column('subUseCase_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subUseCase_roles', 'subUseCase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subUseCase_roles', 'goal')
    op.drop_column('subUseCase_roles', 'motivation')
    op.drop_column('subUseCase_roles', 'id')
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('READ', 'WRITE', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('READ', 'WRITE', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
