"""added goal to sub use case

Revision ID: 8b74282f51ca
Revises: a51df522d6ec
Create Date: 2026-04-09 07:54:48.066574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b74282f51ca'
down_revision: Union[str, Sequence[str], None] = 'a51df522d6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subUseCases', sa.Column('goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subUseCases', 'goal')
    # ### end Alembic commands ###
