"""add transaction_properties

Revision ID: c8db1801147b
Revises: 3e877b8134ba
Create Date: 2026-04-28 13:39:58.133423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8db1801147b'
down_revision: Union[str, Sequence[str], None] = '3e877b8134ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_properties',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('property_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['property_uuid'], ['properties.UUID'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'property_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_properties')
    # ### end Alembic commands ###
