"""added template fields to usecase

Revision ID: ec428c55e044
Revises: 1e210cc245e7
Create Date: 2026-04-21 10:12:11.298783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec428c55e044'
down_revision: Union[str, Sequence[str], None] = '1e210cc245e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useCases', sa.Column('relation_to_other_useCases', sa.String(), nullable=True))
    op.add_column('useCases', sa.Column('uc_owner_institution', sa.String(), nullable=True))
    op.add_column('useCases', sa.Column('uc_owner', sa.String(), nullable=True))
    op.add_column('useCases', sa.Column('conx_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useCases', 'conx_id')
    op.drop_column('useCases', 'uc_owner')
    op.drop_column('useCases', 'uc_owner_institution')
    op.drop_column('useCases', 'relation_to_other_useCases')
    # ### end Alembic commands ###
