"""updated standards

Revision ID: fa76906a529d
Revises: c8db1801147b
Create Date: 2026-06-01 11:50:24.247209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fa76906a529d'
down_revision: Union[str, Sequence[str], None] = 'c8db1801147b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

standardcategory_enum = postgresql.ENUM(
    'FILE_FORMAT',
    'DATA_STANDARD',
    'EUROPEAN_GUIDELINE',
    'EUROPEAN_REGULATION',
    'EUROPEAN_STANDARD',
    'GUIDELINE',
    'INTERNATIONAL_GUIDELINE',
    'INTERNATIONAL_STANDARD',
    'NATIONAL_GUIDELINE',
    'NATIONAL_LAW',
    'NATIONAL_STANDARD',
    'ONTOLOGY',
    'SPECIALIST_BOOK',
    'TECHNICAL_REPORT',
    'TECHNICAL_STANDARD',
    'WORKING_GROUP',
    name='standardcategory'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    standardcategory_enum.create(op.get_bind(), checkfirst=True)


    op.create_table('useCase_standards',
    sa.Column('useCase_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.ForeignKeyConstraint(['useCase_id'], ['useCases.id'], ),
    sa.PrimaryKeyConstraint('useCase_id', 'standard_id')
    )
    op.add_column(
        'standards',
        sa.Column(
            'category',
            sa.Enum(
                'FILE_FORMAT',
                'DATA_STANDARD',
                'EUROPEAN_GUIDELINE',
                'EUROPEAN_REGULATION',
                'EUROPEAN_STANDARD',
                'GUIDELINE',
                'INTERNATIONAL_GUIDELINE',
                'INTERNATIONAL_STANDARD',
                'NATIONAL_GUIDELINE',
                'NATIONAL_LAW',
                'NATIONAL_STANDARD',
                'ONTOLOGY',
                'SPECIALIST_BOOK',
                'TECHNICAL_REPORT',
                'TECHNICAL_STANDARD',
                'WORKING_GROUP',
                name='standardcategory'
            ),
            nullable=False,
            server_default='TECHNICAL_STANDARD'
        )
    )
    op.alter_column('standards', 'category', server_default=None)
    op.add_column('standards', sa.Column('reference_URL', sa.String(), nullable=True))
    op.alter_column('standards', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('standards', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('standards', 'date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('standards', 'reference_URL')
    op.drop_column('standards', 'category')
    op.drop_table('useCase_standards')

    standardcategory_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
