backend:
  image:
    repository: ghcr.io/project-construct-x/usecase-management-backend
    tag: latest
  storage:
    size: 30Gi

frontend:
  image:
    repository: ghcr.io/project-construct-x/usecase-management-frontend
    tag: latest

ingress:
  host: usecase-management.staging.construct-x.net

db:
  user: "user"
  password: "dev_pass_user1"
  db: "appdb_dev_user1"
  storage:
    size: 30Gi
